language: python
python:
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: sjoerdk
  password:
    secure: avEcDKIN06CUItxajdycXaRqxXlPJAzQ0O2KGj+NEwDxOyqMBEBKWXW4SVVij+gHXXt1RaB+XyCC2PlkfF9B/x40Fw9KMzX1WaspxOzn4Nb8WMMIOFm4ypCmCpqgkNkvfElY+H2SYllgwe2I5diNx6Vnc/9XCgqwjc1vcAlnZ3uFbv+khf4R5aypDe8TppP1RyKpI24G8qAO8uBZZvJ0cGekzpYZLO2oUoroAZ8SLVL8ZFCYGCcb5Lk2x/DHWoBgMoN+pL0OXOi8CF+Ww+7iC1tS5cXumfktsw+ObZDGrjuWRptnlyUI5SM4dwCDqqV6H+yLWRMHve3WDEiJGQW9RshkoY9zWgnCLq6i+R+KUCJ9x0lJEnkzPaE0Y7ksZq8TROhpKrMHwehd69DsCYYaU6pqOUVf9/KJCqj/5nfE0LqrX67MdN31sJpElgB5vZfjhTWfg7pWqQplpqUHvBXpAgEI8mqh2z6E18L0ZerPp4fK86lFj+QYGzWxapJkHGS/WcHTAhP1Ooeq9UJd2Yp85KmHWuUNNJ3Xz8ID0PRxejIHVz/iOe+9BaZ9q9qfDJx5e6eELmvejRm2f2VXh3lXBqnZ/F4cmJ61vZEEOK3zH7GVUMmS0O/pBkb26MTKEPiVMOS12FSWIPZwme+NraB+68yX3BhYUoQXS1ANpTNOp8c=
  on:
    tags: true
    repo: sjoerdk/pimsclient
    python: 3.7
